// Plan Tiers
export const PRICE_EXECUTION_PACK_CENTS = 3900; // $39.00
export const PRICE_EXECUTIVE_LICENSE_CENTS = 9900; // $99.00

export const DISPLAY_EXECUTION_PACK = '$39';
export const DISPLAY_EXECUTIVE_LICENSE = '$99';

// Legacy (for transitions)
export const EXECUTION_PACK_PRICE_CENTS = PRICE_EXECUTION_PACK_CENTS;
export const EXECUTION_PACK_PRICE_DISPLAY = DISPLAY_EXECUTION_PACK;
